apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: error-alerts
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'