---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana-loki
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./addons/overlays/development/grafana-loki
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

