---
apiVersion: v1
kind: Namespace
metadata:
  name: dev1
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: selenium-grid
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager