---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 1m0s
  path: ./addons/overlays/development/promtail
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

