apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/rabbitmq

patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: dev1
    target:
      kind: HelmRelease
      name: rabbitmq

patchesStrategicMerge:
- release-patch.yaml