apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/prometheus-stack

patches:
  - target:
      kind: HelmRelease
      name: prometheus-stack
    patch: |-
      - op: remove
        path: /spec/values/grafana/envFromSecrets
      - op: remove
        path: /spec/values/grafana/grafana.ini
      - op: remove
        path: /spec/values/grafana/admin

patchesStrategicMerge:
- release-patch.yaml