apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  values:
    grafana:
      ingress:
        ingressClassName: nginx
        hosts:
          - grafana.dev1.devops.com
      grafana.ini:
        server:
          domain: grafana.dev1.devops.com
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.dev1.devops.com
      prometheusSpec:
        externalLabels:
          cluster: development
        remoteWrite:
        - url: http://mimir-gateway.devops.com/api/v1/push
          headers:
            X-Scope-OrgID: soarian-development
      
      
      