apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  values:
    prometheus:
      prometheusSpec:
        externalLabels:
          cluster: development
      
      