apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  values:
    grafana:
      ingress:
        ingressClassName: nginx
        hosts:
          - grafana.dev1.devops.com
    prometheus:
      prometheusSpec:
        externalLabels:
          cluster: development
      
      