---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./addons/overlays/production/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

