---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus-stack
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./addons/overlays/production/prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

