---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 39.0.0
  interval: 1m0s
  values:
    grafana:
      enabled: true
      admin:
        existingSecret: "grafana-credentials"
        userKey: admin-user
        passwordKey: admin-password
      envFromSecrets: 
        - name: grafana-db-credentials
        - name: grafana-smtp-credentials
      grafana.ini:
        database:
          type: mysql
          host: $__env{DB_HOST}
          name: grafana
          user: $__env{DB_USER}
          password: $__env{DB_PASS}
        server:
          protocol: http
          root_url: "%(protocol)s://%(domain)s/"
        smtp:
          enabled: true
          host: $__env{SMTP_HOST}
          user: $__env{SMTP_USER}
          password: $__env{SMTP_PASS}
          from_address: $__env{SMTP_EMAIL}
      imageRenderer:
        enabled: true
      ingress:
        enabled: true
    prometheus:
      prometheusSpec:
        retention: 5d
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
        # serviceMonitorSelector:
        #   matchLabels:
        #     app.kubernetes.io/name: rabbitmq
