---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  values:
    config:
      clients:
        - url: http://loki-gateway.devops.com/loki/api/v1/push
          tenant_id: soarian-development
          basic_auth:
            username: admin
            password_file: /etc/loki-credentials
    
    extraVolumes:
      - name: my-secret
        secret:
          secretName: loki-credentials
    
    extraVolumeMounts:
      - name: my-secret
        mountPath: "/etc/loki-credentials"
        readOnly: true
